var nationalities = [
	'Afghans',
	'Albanians',
	'Algerians',
	'Americans',
	'Andorrans',
	'Angolans',
	'Argentines',
	'Armenians',
	'Aromanians',
	'Arubans',
	'Australians',
	'Austrians',
	'Azeris',
	'Bahamians',
	'Bahrainis',
	'Bangladeshis',
	'Barbadians',
	'Belarusians',
	'Belgians',
	'Belizeans',
	'Bermudians',
	'Boers',
	'Bosnians',
	'Brazilians',
	'Bretons',
	'British',
	'British Virgin Islanders',
	'Bulgarians',
	'Burkinabès',
	'Burundians',
	'Cambodians',
	'Cameroonians',
	'Canadians',
	'Catalans',
	'Cape Verdeans',
	'Chadians',
	'Chileans',
	'Chinese',
	'Comorians',
	'Congolese',
	'Croatians',
	'Cubans',
	'Cypriots',
	'Turkish Cypriots',
	'Czechs',
	'Danes',
	'Dominicans (Republic)',
	'Dominicans (Commonwealth)',
	'Dutch',
	'East Timorese',
	'Ecuadorians',
	'Egyptians',
	'Emiratis',
	'English',
	'Eritreans',
	'Estonians',
	'Ethiopians',
	'Faroese',
	'Finns',
	'Finnish Swedish',
	'Fijians',
	'Filipinos',
	'French citizens',
	'Georgians',
	'Germans',
	'Baltic Germans',
	'Ghanaians',
	'Gibraltar',
	'Greeks',
	'Grenadians',
	'Guatemalans',
	'Guianese (French)',
	'Guineans',
	'Guinea-Bissau nationals',
	'Guyanese',
	'Haitians',
	'Hondurans',
	'Hungarians',
	'Icelanders',
	'Indians',
	'Indonesians',
	'Iranians (Persians)',
	'Iraqis',
	'Irish',
	'Israelis',
	'Italians',
	'Ivoirians',
	'Jamaicans',
	'Japanese',
	'Jordanians',
	'Kazakhs',
	'Kenyans',
	'Koreans',
	'Kosovo Albanians',
	'Kuwaitis',
	'Lao',
	'Latvians',
	'Lebanese',
	'Liberians',
	'Libyans',
	'Liechtensteiners',
	'Lithuanians',
	'Luxembourgers',
	'Macedonians',
	'Malawians',
	'Maldivians',
	'Malians',
	'Maltese',
	'Manx',
	'Mauritians',
	'Mexicans',
	'Moldovans',
	'Moroccans',
	'Mongolians',
	'Montenegrins',
	'Namibians',
	'Nepalese',
	'New Zealanders',
	'Nicaraguans',
	'Nigeriens',
	'Nigerians',
	'Norwegians',
	'Pakistanis',
	'Palauans',
	'Palestinians',
	'Panamanians',
	'Papua New Guineans',
	'Paraguayans',
	'Peruvians',
	'Poles',
	'Portuguese',
	'Puerto Ricans',
	'Quebecers',
	'Réunionnais',
	'Romanians',
	'Russians',
	'Baltic Russians',
	'Rwandans',
	'Salvadorans',
	'São Tomé and Príncipe',
	'Saudis',
	'Scots',
	'Senegalese',
	'Serbs',
	'Sierra Leoneans',
	'Sikhs',
	'Singaporeans',
	'Slovaks',
	'Slovenes',
	'Somalis',
	'South Africans',
	'Spaniards',
	'Sri Lankans',
	'St Lucians',
	'Sudanese',
	'Surinamese',
	'Swedes',
	'Swiss',
	'Syrians',
	'Taiwanese',
	'Tanzanians',
	'Thais',
	'Tibetans',
	'Tobagonians',
	'Trinidadians',
	'Turks',
	'Tuvaluans',
	'Ugandans',
	'Ukrainians',
	'Uruguayans',
	'Uzbeks',
	'Vanuatuans',
	'Venezuelans',
	'Vietnamese',
	'Welsh',
	'Yemenis',
	'Zambians',
	'Zimbabweans'
];

Template.bookus.helpers({
	'nationalities' : nationalities
});